#local, dev, prod 공통 설정
application:
  version: 1.0.0
  title: my-api-server

server:
  port: 8080

spring:
  profiles:
    active: local #local 환경을 기본으로 사용
  datasource: #db 접속 정보
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    url: jdbc:${DB_KIND}:${DB_DELIMITER}${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&currentSchema=${DB_SCHEMA_NAME}
    postgres:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      database: digest_db
  jpa: # jpa properties
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    open-in-view: false
    generate-ddl: true
logging:
  level:
    root: debug

--- #dev 환경
spring:
  profiles: dev
logging:
  level:
    root: info

--- #prod 환경
spring:
  profiles: prod
logging:
  level:
    root: error